import type { MSG } from "../../types/msgData.d.ts";

function getLogs(overrides?:any):any{
	 return {
		projectKey:"test_key_1",
		...overrides,
		logs:[
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"fatal", msg:`Server is down`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"debug", msg:`Notification service down`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"debug", msg:`Notification service down`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"debug", msg:`Notification service down`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"fatal", msg:`Server is down`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"fatal", msg:`Server is down`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"debug", msg:`Notification service down`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"fatal", msg:`Server is down`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"debug", msg:`Notification service down`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"debug", msg:`Notification service down`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"debug", msg:`Notification service down`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"fatal", msg:`Server is down`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"debug", msg:`Notification service down`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"debug", msg:`Notification service down`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"fatal", msg:`Server is down`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"debug", msg:`Notification service down`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"fatal", msg:`Server is down`, meta:{}},
			{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
			{lvl:"debug", msg:`Notification service down`, meta:{}},
			{lvl:"fatal", msg:`Payement service failure`, meta:{}},
			{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		]
	};
}
const logs:Array<MSG> = [
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"fatal", msg:`Server is down`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"debug", msg:`Notification service down`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"debug", msg:`Notification service down`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"debug", msg:`Notification service down`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"fatal", msg:`Server is down`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"fatal", msg:`Server is down`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"debug", msg:`Notification service down`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"fatal", msg:`Server is down`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"debug", msg:`Notification service down`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"debug", msg:`Notification service down`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"debug", msg:`Notification service down`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"fatal", msg:`Server is down`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"debug", msg:`Notification service down`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"debug", msg:`Notification service down`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"warn", msg:`Redis server buffered: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"fatal", msg:`Server is down`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"debug", msg:`Notification service down`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"fatal", msg:`Server is down`, meta:{}},
		{lvl:"info", msg:`Server is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"info", msg:`Redis is running: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
		{lvl:"debug", msg:`Notification service down`, meta:{}},
		{lvl:"fatal", msg:`Payement service failure`, meta:{}},
		{lvl:"info", msg:`Payment Service is online: ${new Date(Date.now()).toISOString().split("T")[0]}`, meta:{}},
	]

export { logs, getLogs };
